---
- hosts:  '{{ target }}'
  tasks:
    - name: uninstall virtualenv if needed
      become: True
      pip:
        name: virtualenv
        state:  absent
    - name: delete virtualenv
      file:
        path: /home/{{ ansible_user }}/taxidata
        state:  absent
    - name: delete cron
      cron:
        user: '{{ ansible_user }}'
        name: "fetch data"
        state:  absent