---
- hosts:  '{{ target }}'
  become: True
  tasks:
    - name: install python dev if needed
      apt:
        name: python-dev
        state:  present
    - name: install virtualenv if needed
      pip:
        name: virtualenv
    - name: create virtualenv
      pip:
        name: requests, pandas
        virtualenv: /home/pi/taxidata
    - name: checkout or update from git
      git:
        repo: 'https://github.com/hari-allamraju/sg-taxidata.git'
        dest: /home/pi/taxidata
    - name: setup cron
      cron:
        name: "fetch data"
        minute: "/5"
        job: "bash /home/pi/taxidata/sg-taxidata/run.sh"