---
- hosts:  '{{ target }}'
  tasks:
    - name: install python dev if needed
      become: True
      apt:
        name: python-dev
        state:  present
    - name: install virtualenv if needed
      become: True
      pip:
        name: virtualenv
    - name: install packages
      become: True
      pip:
        name: requests xmljson
    - name: install pandas if needed
      become: True
      apt:
        name: python-pandas
        state:  present
    - name: create virtualenv
      pip:
        #requirements will come later from git
        name: pip
        virtualenv: '/home/{{ ansible_user }}/taxidata'
        virtualenv_site_packages: yes
    - name: checkout or update from git
      git:
        repo: 'https://github.com/hari-allamraju/sg-taxidata.git'
        dest: '/home/{{ ansible_user}}/taxidata/sg-taxidata'
    - name: setup cron
      cron:
        user: '{{ ansible_user }}'
        name: "fetch data"
        minute: "*/5"
        job: 'bash /home/{{ ansible_user }}/taxidata/sg-taxidata/run.sh'
    - name: setup weather cron
      cron:
        user: '{{ ansible_user }}'
        name: "fetch weather data"
        minute: "0"
        job: 'bash /home/{{ ansible_user }}/taxidata/sg-taxidata/run_weather.sh'
